services:
  backend:
    build: ./backend
    container_name: url-shortener-backend

    labels:
      - traefik.enable=true
      - traefik.http.routers.shorturl.rule=Host(`shorturl.${TRAEFIK_HOST}`)
      - traefik.http.routers.shorturl.entrypoints=websecure
      - traefik.http.routers.shorturl.tls.certresolver=letsencrypt
      - traefik.http.services.shorturl.loadbalancer.server.port=3000

    depends_on:
      - mongodb

    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - CORS_ORIGIN=*

    restart: always

    networks:
      - url-shortener-network

  mongodb:
    image: mongo:latest
    container_name: url-shortener-mongodb
    hostname: mongodb
    restart: unless-stopped

    volumes:
      - mongo-data:/data/db

    networks:
      - url-shortener-network

volumes:
  mongo-data:

networks:
  url-shortener-network:
    driver: bridge
